import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { RunnerToolDef } from "../primitives/runtime.ts";

// Build an opencode plugin module that exposes every workflow-registered
// runner tool to opencode UNDER ITS BARE NAME (no MCP server prefix). The
// plugin file is loaded by opencode via the `plugin` config option as a
// file:// path. Each tool's `execute` callback POSTs { name, args } to the
// RunnerToolServer's /rpc/call endpoint and returns the JSON-encoded result
// as the tool output the model sees.
//
// Why this exists: opencode prefixes MCP tools as `<server>_<tool>` when
// exposing them to the model. With `__runner__` as the server name, a tool
// named `report_file_status` reaches the model as
// `__runner___report_file_status` — long and easy for the model to garble
// (it routinely hallucinates `report_file_status`, the bare name, in
// response). opencode plugin tools, on the other hand, register UNDER THE
// EXACT KEY the plugin returns. So a plugin exporting
//   { tool: { report_file_status: ... } }
// makes the tool visible as just `report_file_status`. That is the entire
// reason the runner generates a plugin file instead of relying on MCP.
//
// The plugin file is plain ES modules with ZERO external imports. It does
// not import zod, @opencode-ai/plugin, or anything else: opencode's plugin
// loader detects a plugin tool purely by structural typing —
//   isPluginTool(v) = "args" in v && "description" in v && "execute" in v
// — so we emit object literals directly. Avoiding all imports also dodges
// the open question of how to make `node_modules/@opencode-ai/plugin`
// resolvable from whichever directory the runner writes the plugin file
// to. Tool args are described via JSON Schema entries; opencode's plugin
// registry treats non-Zod args as "legacy" JSON Schema and builds the
// tool's inputSchema from them. Because legacy mode marks every listed
// property as required, optional fields from the workflow's inputSchema
// get expressed as nullable JSON Schema types ({ "type": ["string", "null"] })
// so the model can still pass `null` to skip them.

export interface RunnerPluginFileOptions {
  // Absolute file path to write the plugin module to. Parent dir is
  // created with recursive:true.
  destPath: string;
  // Full URL of the RunnerToolServer's /rpc/call endpoint that the plugin
  // POSTs to.
  rpcUrl: string;
  // Tool definitions to export. Iteration order is preserved in the
  // generated file for byte-stable output across reruns.
  tools: RunnerToolDef[];
  // Stable plugin id reported in the default export. opencode's path-style
  // plugin loader requires this.
  pluginId?: string;
}

// Generate the plugin file content (as a string) without writing it. Useful
// for tests that want to assert on the emitted module shape without
// touching the filesystem.
export function renderRunnerPluginFile(opts: RunnerPluginFileOptions): string {
  const pluginId = opts.pluginId ?? "agent-runner-tools";

  // For each tool, emit:
  //   <toolName>: tool({ description, args, execute })
  //
  // - `description` is the workflow-provided description string.
  // - `args` is a record of { propName: jsonSchema } built from the
  //   workflow's inputSchema. Optional properties (not listed in
  //   inputSchema.required) get { "type": [origType, "null"] } so opencode's
  //   "every-arg-required" legacy schema still lets the model skip them.
  // - `execute` POSTs { name, args } to the RPC URL and returns the
  //   JSON-stringified server response as the tool output.
  const toolEntries = opts.tools.map((def) => {
    const args = buildLegacyArgsRecord(def.inputSchema);
    const descriptionJson = JSON.stringify(def.description);
    const nameJson = JSON.stringify(def.name);
    const argsJson = JSON.stringify(args, null, 6).replace(/\n/g, "\n    ");
    return `    ${jsKey(def.name)}: {
      description: ${descriptionJson},
      args: ${argsJson},
      async execute(callArgs) {
        const res = await fetch(RPC_URL, {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ name: ${nameJson}, args: callArgs ?? {} }),
        });
        if (!res.ok) {
          return "runner-rpc HTTP " + res.status + ": " + (await res.text());
        }
        const payload = await res.json();
        if (payload && payload.ok === false) {
          return "runner-rpc error: " + (payload.error || "(no error)");
        }
        const result = payload && Object.prototype.hasOwnProperty.call(payload, "result")
          ? payload.result
          : payload;
        return typeof result === "string" ? result : JSON.stringify(result, null, 2);
      },
    },`;
  });

  return `// Auto-generated by agent_runner (src/driver/RunnerPluginFile.ts).
// DO NOT HAND-EDIT — every run regenerates this file. The file is loaded
// by opencode as a path-style plugin (see opencode's plugin config). Each
// tool registered here is visible to the model UNDER ITS BARE NAME with no
// MCP server prefix. See RunnerPluginFile.ts for the rationale.

const RPC_URL = ${JSON.stringify(opts.rpcUrl)};

const server = async () => ({
  tool: {
${toolEntries.join("\n")}
  },
});

export default { id: ${JSON.stringify(pluginId)}, server };
`;
}

// Write the plugin file to disk and return the absolute path. The caller
// passes this path to opencode via the `plugin` config option (as a
// path-style spec — file:// URL or absolute path are both accepted by
// opencode's plugin loader).
export async function writeRunnerPluginFile(opts: RunnerPluginFileOptions): Promise<string> {
  const abs = path.resolve(opts.destPath);
  await mkdir(path.dirname(abs), { recursive: true });
  const content = renderRunnerPluginFile(opts);
  await writeFile(abs, content, "utf8");
  return abs;
}

// Translate the workflow's JSON Schema for a tool's input into the
// per-arg record opencode's "legacy" plugin tool path expects. The schema
// must have `type: "object"`. Optional properties (not in `required`) get
// their `type` widened to include `"null"` so the model has a permitted way
// to skip them under opencode's all-args-required legacy schema.
function buildLegacyArgsRecord(
  schema: { type: "object"; properties?: Record<string, unknown>; required?: string[]; [k: string]: unknown },
): Record<string, unknown> {
  const properties = (schema.properties && typeof schema.properties === "object")
    ? schema.properties as Record<string, unknown>
    : {};
  const required = new Set(Array.isArray(schema.required) ? schema.required : []);
  const out: Record<string, unknown> = {};
  for (const [propName, propSchemaRaw] of Object.entries(properties)) {
    if (typeof propSchemaRaw !== "object" || propSchemaRaw === null) {
      // Treat non-object property schemas as opaque pass-through so we
      // never silently drop fields the workflow author declared.
      out[propName] = propSchemaRaw;
      continue;
    }
    const propSchema = propSchemaRaw as Record<string, unknown>;
    if (required.has(propName)) {
      out[propName] = propSchema;
    } else {
      out[propName] = widenWithNull(propSchema);
    }
  }
  return out;
}

// Add "null" to a property's allowed types so an "all-required" legacy
// schema can still permit the model to omit the field by passing null.
// If `type` is missing we leave the schema alone — the model has nothing
// concrete to validate against either way.
function widenWithNull(propSchema: Record<string, unknown>): Record<string, unknown> {
  const t = propSchema.type;
  if (typeof t === "string") {
    if (t === "null") return propSchema;
    return { ...propSchema, type: [t, "null"] };
  }
  if (Array.isArray(t)) {
    if (t.includes("null")) return propSchema;
    return { ...propSchema, type: [...t, "null"] };
  }
  return propSchema;
}

// Generate a safe JS object-literal key for a tool name. Tool names are
// validated by defineTool() against /[A-Za-z0-9_.-]+/, which means a name
// can include `.` or `-` that would break a bare identifier in JS. We
// always emit a quoted string key to sidestep the issue.
function jsKey(name: string): string {
  return JSON.stringify(name);
}
